---
- name: Testing andrewrothstein.critools
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'crictl --version'
      ansible.builtin.command: crictl --version
      changed_when: false
      register: crictl_test_output
    - name: Output from 'crictl --version'
      ansible.builtin.debug:
        msg: '{{ crictl_test_output.stdout }}'
