---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/crictl --version
      register: crictl_test_output
    - name: crictl --version
      debug:
        msg: '{{ crictl_test_output.stdout }}'
