---
- name: Resolving vars for {{ critools_app }}:{{ critools_ver }}
  ansible.builtin.include_vars:
    file: app-vars.yml
- name: Looking install at {{ critools_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ critools_install_exe }}'
  changed_when: false
  register: critools_binary
- name: Downloading and installing {{ critools_app }}
  when: not critools_binary.stat.exists
  block:
    - name: Downloading {{ critools_url }} to {{ critools_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ critools_url }}'
        dest: '{{ critools_tmp_archive }}'
        mode: '644'
        checksum: '{{ critools_checksum }}'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchiving {{ critools_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ critools_tmp_archive }}'
        dest: '{{ critools_install_dir }}'
        creates: '{{ critools_install_exe }}'
  always:
    - name: Rm {{ critools_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ critools_tmp_archive }}'
        state: absent
- name: Linking {{ critools_link }} to {{ critools_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ critools_install_exe }}'
    dest: '{{ critools_link }}'
    state: link
